In [56]:
import pandas as pd
from pathlib import Path
import csv
import requests
import json

In [57]:
movie_file = Path("IMDB_All_Genres_etf_clean1.csv")

movie_df = pd.read_csv(movie_file)

movie_df.head()

,Movie_Title,Year,Director,Actors,Rating,Runtime(Mins),Censor,Total_Gross,main_genre,side_genre
0,Kantara,2022,Rishab Shetty,"Rishab Shetty, Sapthami Gowda, Kishore Kumar G...",9.3,148,UA,Gross Unkown,Action,"Adventure, Drama"
1,The Dark Knight,2008,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",9.0,152,UA,$534.86M,Action,"Crime, Drama"
2,The Lord of the Rings: The Return of the King,2003,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",9.0,201,U,$377.85M,Action,"Adventure, Drama"
3,Inception,2010,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",8.8,148,UA,$292.58M,Action,"Adventure, Sci-Fi"
4,The Lord of the Rings: The Two Towers,2002,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",8.8,179,UA,$342.55M,Action,"Adventure, Drama"

In [58]:
movie_df[["Movie Rated","Language","Awards","Rotten Tomatoes Rating","IMDb Rating","Metascore","IMDb ID","Box Office"]] = ""

movie_df.head()

,Movie_Title,Year,Director,Actors,Rating,Runtime(Mins),Censor,Total_Gross,main_genre,side_genre,Movie Rated,Language,Awards,Rotten Tomatoes Rating,IMDb Rating,Metascore,IMDb ID,Box Office
0,Kantara,2022,Rishab Shetty,"Rishab Shetty, Sapthami Gowda, Kishore Kumar G...",9.3,148,UA,Gross Unkown,Action,"Adventure, Drama",,,,,,,,
1,The Dark Knight,2008,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",9.0,152,UA,$534.86M,Action,"Crime, Drama",,,,,,,,
2,The Lord of the Rings: The Return of the King,2003,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",9.0,201,U,$377.85M,Action,"Adventure, Drama",,,,,,,,
3,Inception,2010,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",8.8,148,UA,$292.58M,Action,"Adventure, Sci-Fi",,,,,,,,
4,The Lord of the Rings: The Two Towers,2002,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",8.8,179,UA,$342.55M,Action,"Adventure, Drama",,,,,,,,

In [59]:
apiKey = "5f8350bc"



for index, row in movie_df.iloc[0:10].iterrows():

    movie = row['Movie_Title']

    base_url = "http://www.omdbapi.com/"
    url = f"{base_url}?t={movie}&apiKey={apiKey}"

    movie_response = requests.get(url)

    movie_json = movie_response.json()

    
    try:
        movie_rated = movie_json["Rated"]
        movie_df.loc[index, "Movie Rated"] = movie_rated
    except KeyError:
        movie_df.loc[index, "Movie Rated"] = "Rating not found"

    try:
        movie_rated = movie_json["Language"]
        movie_df.loc[index, "Language"] = movie_rated
    except KeyError:
        movie_df.loc[index, "Language"] = "Language not found"

movie_df.head(15)

,Movie_Title,Year,Director,Actors,Rating,Runtime(Mins),Censor,Total_Gross,main_genre,side_genre,Movie Rated,Language,Awards,Rotten Tomatoes Rating,IMDb Rating,Metascore,IMDb ID,Box Office
0,Kantara,2022,Rishab Shetty,"Rishab Shetty, Sapthami Gowda, Kishore Kumar G...",9.3,148,UA,Gross Unkown,Action,"Adventure, Drama",Not Rated,Kannada,,,,,,
1,The Dark Knight,2008,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",9.0,152,UA,$534.86M,Action,"Crime, Drama",PG-13,"English, Mandarin",,,,,,
2,The Lord of the Rings: The Return of the King,2003,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",9.0,201,U,$377.85M,Action,"Adventure, Drama",PG-13,"English, Quenya, Old English, Sindarin",,,,,,
3,Inception,2010,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",8.8,148,UA,$292.58M,Action,"Adventure, Sci-Fi",PG-13,"English, Japanese, French",,,,,,
4,The Lord of the Rings: The Two Towers,2002,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",8.8,179,UA,$342.55M,Action,"Adventure, Drama",PG-13,"English, Sindarin, Old English",,,,,,
5,The Lord of the Rings: The Fellowship of the Ring,2001,Peter Jackson,"Elijah Wood, Ian McKellen, Orlando Bloom, Sean...",8.8,178,U,$315.54M,Action,"Adventure, Drama",PG-13,"English, Sindarin",,,,,,
6,The Matrix,1999,"Directors:Lana Wachowski, Lilly Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...",8.7,136,A,$171.48M,Action,Sci-Fi,R,English,,,,,,
7,The Empire Strikes Back,1980,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher, Bil...",8.7,124,UA,$290.48M,Action,"Adventure, Fantasy",PG,English,,,,,,
8,Terminator 2: Judgment Day,1991,James Cameron,"Arnold Schwarzenegger, Linda Hamilton, Edward ...",8.6,137,A,$204.84M,Action,Sci-Fi,R,"English, Spanish",,,,,,
9,Star Wars,1977,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher, Ale...",8.6,121,U,$322.74M,Action,"Adventure, Fantasy",PG,English,,,,,,
10,Seppuku,1962,Masaki Kobayashi,"Tatsuya Nakadai, Akira Ishihama, Shima Iwashit...",8.6,133,Not Rated,Gross Unkown,Action,"Drama, Mystery",,,,,,,,
11,Shichinin no samurai,1954,Akira Kurosawa,"Toshirô Mifune, Takashi Shimura, Keiko Tsushim...",8.6,207,U,$0.27M,Action,Drama,,,,,,,,
12,Kaithi,2019,Lokesh Kanagaraj,"Karthi, Narain, Arjun Das, George Maryan",8.5,145,UA,Gross Unkown,Action,"Adventure, Crime",,,,,,,,
13,Asuran,2019,Vetrimaaran,"Dhanush, Manju Warrier, Prakash Raj, Pasupathy",8.5,141,UA,Gross Unkown,Action,Drama,,,,,,,,
14,Sita Ramam,2022,Hanu Raghavapudi,"Dulquer Salmaan, Mrunal Thakur, Rashmika Manda...",8.5,163,U,Gross Unkown,Action,"Drama, Mystery",,,,,,,,

In [21]:
base_url = "http://www.omdbapi.com/?t=Kantara"
    
movie_response = requests.get(base_url, params=params)

movie_json = movie_response.json()

print(json.dumps(movie_json, indent=4, sort_keys=True))

{
    "Actors": "Rishab Shetty, Kishore Kumar G., Achyuth Kumar",
    "Awards": "12 wins & 8 nominations",
    "BoxOffice": "N/A",
    "Country": "India",
    "DVD": "N/A",
    "Director": "Rishab Shetty",
    "Genre": "Action, Adventure, Drama",
    "Language": "Kannada",
    "Metascore": "N/A",
    "Plot": "When greed paves the way for betrayal, scheming and murder, a young tribal reluctantly dons the traditions of his ancestors to seek justice.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNjQyNGI5OWEtZjI1Yy00NDVjLWE4MTAtMzRlNzU1NzM2OGVkXkEyXkFqcGdeQXVyMTA1NzEzOTU1._V1_SX300.jpg",
    "Production": "N/A",
    "Rated": "Not Rated",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "8.2/10"
        },
        {
            "Source": "Rotten Tomatoes",
            "Value": "80%"
        }
    ],
    "Released": "30 Sep 2022",
    "Response": "True",
    "Runtime": "148 min",
    "Title": "Kantara",
    "Type": "movie",
    "Website": "N/A",
    "Writer": "Shanil Guru, Anirudh Mahesh, Sham Prasad",
    "Year": "2022",
    "imdbID": "tt15327088",
    "imdbRating": "8.2",
    "imdbVotes": "101,767"
}

In [ ]:
{
  "Rated": "PG",
  "Released": "07 Nov 2014",
  "Language": "English",
  "Awards": "Won 1 Oscar. 17 wins & 58 nominations total",
  "Ratings": [
    {
      "Source": "Internet Movie Database",
      "Value": "7.8/10"
    },
    {
      "Source": "Rotten Tomatoes",
      "Value": "90%"
    },
    {
      "Source": "Metacritic",
      "Value": "74/100"
    }
  ],
  "Metascore": "74",
  "imdbRating": "7.8",
  "imdbVotes": "501,565",
  "imdbID": "tt2245084",
  "BoxOffice": "$222,527,828",
}